# Generated by Django 4.2.3 on 2023-08-04 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_service_branch_service_sales_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='subscribers',
        ),
        migrations.AlterField(
            model_name='service',
            name='notifying',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.service')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.subscriber')),
            ],
            options={
                'unique_together': {('service', 'subscriber')},
            },
        ),
    ]
