# Generated by Django 4.2.3 on 2023-08-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_service_subscriptions_service_subscribers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='service',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribed_services', through='webapp.Subscription', to='webapp.subscriber'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_subscriptions', to='webapp.service'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='webapp.subscriber'),
        ),
    ]
